version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
    expose:
      - 5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  rococo_service_processor:
    image: ecorrouge/rococo_service_processor
    container_name: rococo_service_processor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
