# Local rococo-service-base-onbuild image can be build from ../rococo_service_base
# Public image reference is to be changed to the ecorrouge/rococo-service-base-onbuild later
FROM artniki/rococo-service-base-onbuild